wand:
  # Item for wand. Default = STICK.
  material: "stick"

  # Display name for wand. Default = Wand.
  display-name: "The great wand!"
  # Display name coloring. Default = 0x55ff55 (green).
  display-name-color: 0x55ff55

  # Lore for wand. Default = empty.
  lore:
    - "Example lore for wand."
    - "Example second line for wand."
  # Lore coloring. Default = 0xaaaaaa (gray).
  lore-color: 0xaaaaaa