name: MagicMalve
version: 1.0.0
main: io.github.zrdzn.minecraft.magicmalve.MagicMalvePlugin
api-version: 1.17
author: zrdzn
description: Use different spells through magic wand

permissions:
  magicmalve.admin:
    default: op
  magicmalve.wand:
    default: true

commands:
  magicmalve:
    aliases: [ spells ]